-- Create Clients Table
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    nif TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    postal_code TEXT,
    last_purchase TIMESTAMP WITH TIME ZONE
);

-- Create Invoices Table
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    invoice_id TEXT UNIQUE NOT NULL,
    document_type TEXT,
    date TIMESTAMP WITH TIME ZONE,
    entry_date TEXT,
    delivery_date TEXT,
    client_name TEXT,
    client_nif TEXT,
    client_phone TEXT,
    client_email TEXT,
    client_address TEXT,
    client_city TEXT,
    client_zip TEXT,
    items JSONB,
    subtotal NUMERIC,
    iva_applied BOOLEAN,
    iva_total NUMERIC,
    total_general NUMERIC,
    payment_method TEXT,
    paid_status TEXT,
    pdf_url TEXT
);

-- Disable RLS for simplicity (since we are using anon key from frontend)
-- In a production app, you would enable RLS with proper policies
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
